env:
  global:
    - CC_TEST_REPORTER_ID=5da5275dc39f21feb6caca552c80c340804d2856776296cf67f7dbe38e6de910
language: node_js
node_js:
  - "8"
  - "10"
os:
  - linux
  - osx
cache:
  directories:
  - node_modules
  - $HOME/.stack
before_script:
  - mkdir -p $HOME/tmp
  - mkdir -p $HOME/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/${TRAVIS_OS_NAME}-x86_64.tar.gz | tar -xz --strip-components=1 -C $HOME/tmp
  - mv $HOME/tmp/stack $HOME/.local/bin/
  - stack --version
  - stack install brittany
  - brittany --version
  - OS_NAME=$(uname | tr A-Z a-z)
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-${OS_NAME}-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  email:
    on_success: never
    on_failure: change
